apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://p3m-influxdb:8086
    secureJsonData:
      token: admin-token
    jsonData:
      version: Flux
      organization: p3m-org
      defaultBucket: p3m-bucket
      tlsSkipVerify: true
