version: "2"

services:
  uem-postgres:
    image: postgres:14.1
    container_name: uem-postgres
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./config/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uem
      POSTGRES_TEST_DB: uem-test
    networks:
      - uem-backend-net
    restart: unless-stopped

  uem-influxdb:
    image: influxdb:2.1
    container_name: uem-influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb2
      - ./volumes/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: password
      DOCKER_INFLUXDB_INIT_ORG: uem-org
      DOCKER_INFLUXDB_INIT_BUCKET: uem-bucket
    networks:
      - uem-backend-net
    restart: unless-stopped

  uem-telegraf:
    image: telegraf:1.20
    container_name: uem-telegraf
    depends_on:
      - uem-influxdb
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - uem-backend-net
    restart: unless-stopped

  uem-grafana:
    image: grafana/grafana-oss:8.3.2
    container_name: uem-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
    networks:
      - uem-backend-net
    restart: unless-stopped

  uem-test-mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: uem-test-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - uem-backend-net
    restart: unless-stopped

networks:
  uem-backend-net:
