ALTER TABLE devices ADD brightness_min DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE devices ADD brightness_max DOUBLE PRECISION NOT NULL DEFAULT 1000000;
ALTER TABLE devices ADD moisture_counter_min DOUBLE PRECISION NOT NULL DEFAULT 30;
ALTER TABLE devices ADD moisture_counter_max DOUBLE PRECISION NOT NULL DEFAULT 500;
