name: ci-cd

on:
  push:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Start Development Environment
        working-directory: ./deployment/p3m-local-dev
        run: docker-compose up -d

      - name: Execute Maven Tests
        working-directory: ./backend
        run: mvn test --no-transfer-progress

  test-e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Save Secrets to .env-secrets
        working-directory: ./deployment/p3m-local-e2e
        run: echo "$P3M_LOCAL_E2E_SECRETS" > .env-secrets
        env:
          P3M_LOCAL_E2E_SECRETS: ${{ secrets.P3M_LOCAL_E2E_SECRETS }}

      - name: Start Development Environment
        working-directory: ./deployment/p3m-local-e2e
        run: ./deploy-local-e2e.sh

      - name: Sleep for 30 seconds
        run: sleep 30s

      - name: Print logs
        run: docker logs p3m-backend

      - name: Execute End to End Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: e2e

      - name: Upload cypress screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: e2e/cypress/screenshots

      - name: Upload cypress videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: e2e/cypress/videos

  deploy:
    runs-on: ubuntu-latest

    needs: [test-backend, test-e2e]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Save Secrets to .env-secrets
        working-directory: ./deployment/p3m-production
        run: echo "$P3M_PRODUCTION_SECRETS" > .env-secrets
        env:
          P3M_PRODUCTION_SECRETS: ${{ secrets.P3M_PRODUCTION_SECRETS }}

      - name: Perform Deployment
        working-directory: ./deployment/p3m-production
        run: ./deploy-production.sh -fb
